<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>KAOS</AssemblyName>
    <RootNamespace>KAOS</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultItems>false</EnableDefaultItems>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="OpenTK.GLControl" Version="4.8.2" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="AssimpNet" Version="5.0.0-beta1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MataliPhysics">
      <HintPath>..\Dependencies\MataliPhysicsBasic\MataliPhysicsOpenTK\Mono\MataliPhysics\AnyCPU\MataliPhysics.dll</HintPath>
    </Reference>
    <Reference Include="MataliRender">
      <HintPath>..\Dependencies\MataliPhysicsBasic\MataliPhysicsOpenTK\Mono\MataliPhysics\AnyCPU\MataliRender.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Interfaces\IGameObject.cs" />
    <Compile Include="Managers\VertexBufferManager.cs" />
    <Compile Include="Interfaces\IDrawableShape.cs" />
    <Compile Include="Managers\InputManager.cs" />
    <Compile Include="Managers\ShaderManager.cs" />
    <Compile Include="Managers\StateManager.cs" />
    <Compile Include="Managers\TextureManager.cs" />
    <Compile Include="Nodes\GraphLinesNode.cs" />
    <Compile Include="Nodes\PolygonNode.cs" />
    <Compile Include="Shapes\Capsule.cs" />
    <Compile Include="Shapes\ChamferCube.cs" />
    <Compile Include="Shapes\KochTetrahedron.cs" />
    <Compile Include="Shapes\MengerSponge.cs" />
    <Compile Include="Shapes\Old\IsoSphere.cs" />
    <Compile Include="Shapes\Old\Plane.cs" />
    <Compile Include="Shapes\Old\Shape.cs" />
    <Compile Include="Shapes\Old\SierpinskiTetrahedron.cs" />
    <Compile Include="Shapes\SlicedHose.cs" />
    <Compile Include="Shapes\SlicedSphere.cs" />
    <Compile Include="Shapes\TorusKnot.cs" />
    <Compile Include="Shapes\VertexPositionColor.cs" />
    <Compile Include="States\AbstractState.cs" />
    <Compile Include="States\MandelbrotState.cs" />
    <Compile Include="States\ModelState.cs" />
    <Compile Include="States\SceneGraphState.cs" />
    <Compile Include="States\Skyboxstate.cs" />
    <Compile Include="States\VoxelState.cs" />
    <Compile Include="Utilities\VertexBuffer.cs" />
    <Compile Include="Utilities\Camera.cs" />
    <Compile Include="Utilities\Extensions.cs" />
    <Compile Include="Utilities\Logger.cs" />
    <Compile Include="Nodes\GroupNode.cs" />
    <Compile Include="Interfaces\IGroupNode.cs" />
    <Compile Include="Interfaces\ISceneNode.cs" />
    <Compile Include="KAOSEngine.cs" />
    <Compile Include="Shapes\Base\DrawableShape.cs" />
    <Compile Include="Shapes\Base\VertexStructs.cs" />
    <Compile Include="Shapes\Helpers\Chunk.cs" />
    <Compile Include="Shapes\Helpers\MengerCube.cs" />
    <Compile Include="Shapes\Helpers\TetrahedronFace.cs" />
    <Compile Include="Shapes\Helpers\VboShape.cs" />
    <Compile Include="Shapes\Old\Cube.cs" />
    <Compile Include="Nodes\Node.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Utilities\AnimationTimer.cs" />
    <Compile Include="Utilities\Renderer.cs" />
    <Compile Include="Utilities\Shader.cs" />
    <Compile Include="Utilities\TextRenderer.cs" />
    <Compile Include="Utilities\Texture.cs" />
  </ItemGroup>
</Project>
